### ISSUE TITLE
Push panfl to panflute

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/pandoctools#10]
Yep. Push [this](https://github.com/kiwi0fruit/pandoctools/blob/master/pandoctools/panfl/panfl.py).

But if [this original file](https://github.com/sergiocorreia/panflute/commits/master/panflute/autofilter.py) will not change there's no motivation to do so :-)

TO DO:

* [x] move panflute filters declaration to the profile instead of the pipe
* [x] use new pf ability to import modules instead of eval files - remove code from pf filters
* [x] check if pipe can be stored in the air
* [x] set default values in arg script. They can be overriden in the profile. Write about  it.
* [x] ~set `panflute>1.11.0` in sugartex~ and `sugartex>0.1.11` and `panflute>1.11.0` in pandoctools
* [x] test on unix

**Comment by kiwi0fruit** [comment]
@sergiocorreia I thought about pushing it to panflute but it uses click. Panflute doesn't use it so adding an extra dep is not a good idea. And I'm not going to rewrite it without click.

So I'm closing it for now.

**Comment by sergiocorreia** [comment]
@kiwi0fruit tbf I wouldn't mind adding click as a dependency. It's a well supported dep and easy to work with.
